;*****************************************************************************
;*		底层核心文件Kernel.asm				    *
;*				彭东 
;*****************************************************************************

%include "HalEIIntoPoint.h"
[section .hwint.text]
[BITS 64]

ALIGN	16
HalExCDivideError:
	SRFTFAULT 0
ALIGN	16
HalExCSingleStepException:
	SRFTFAULT 1
ALIGN	16
HalExCnmi:
	SRFTFAULT 2
ALIGN	16
HalExCBreakPointException:
	SRFTFAULT 3
ALIGN	16
HalExCOverflow:
	SRFTFAULT 4
ALIGN	16
HalExCBoundsCheck:
	SRFTFAULT 5
ALIGN	16
HalExCInvalOPCode:
	SRFTFAULT 6
ALIGN	16
HalExCCoprNotAvailable:
	SRFTFAULT 7
ALIGN	16
HalExCDoubleFault:
	SRFTFAULT_ECODE 8
ALIGN	16
HalExCCoprSegOverrun:
	SRFTFAULT 9
ALIGN	16
HalExCInvalTSS:
	SRFTFAULT_ECODE 10
ALIGN	16
HalExCSegmentNotPresent:
	SRFTFAULT_ECODE 11
ALIGN	16
HalExCStackException:
	SRFTFAULT_ECODE 12
ALIGN	16
HalExCGeneralProtection:
	SRFTFAULT_ECODE 13
ALIGN	16
HalExCPageFault:
	SRFTFAULT_ECODE 14
ALIGN	16
HalExCCoprError:
	SRFTFAULT 16
ALIGN	16
HalExCAlignmentCheck:
	SRFTFAULT_ECODE 17
ALIGN	16
HalExCMachineCheck:
	SRFTFAULT 18
ALIGN	16
HalExCSimdFault:
	SRFTFAULT 19
ALIGN	16
HalExCOSDefaultFaultHandle:
	SRFTFAULT 256
	
	
ALIGN	16
HalExIHWINT00:
	HARWINT	(INT_VECTOR_IRQ0+0)
ALIGN	16
HalExIHWINT01:
	HARWINT	(INT_VECTOR_IRQ0+1)
ALIGN	16
HalExIHWINT02:
	HARWINT	(INT_VECTOR_IRQ0+2)
ALIGN	16
HalExIHWINT03:
	HARWINT	(INT_VECTOR_IRQ0+3)
ALIGN	16
HalExIHWINT04:
	HARWINT	(INT_VECTOR_IRQ0+4)
ALIGN	16
HalExIHWINT05:
	HARWINT	(INT_VECTOR_IRQ0+5)
ALIGN	16
HalExIHWINT06:
	HARWINT	(INT_VECTOR_IRQ0+6)
ALIGN	16
HalExIHWINT07:
	HARWINT	(INT_VECTOR_IRQ0+7)
ALIGN	16
HalExIHWINT08:
	HARWINT	(INT_VECTOR_IRQ0+8)
ALIGN	16
HalExIHWINT09:
	HARWINT	(INT_VECTOR_IRQ0+9)
ALIGN	16
HalExIHWINT10:
	HARWINT	(INT_VECTOR_IRQ0+10)
ALIGN	16
HalExIHWINT11:
	HARWINT	(INT_VECTOR_IRQ0+11)
ALIGN	16
HalExIHWINT12:
	HARWINT	(INT_VECTOR_IRQ0+12)

ALIGN	16
HalExIHWINT13:
	HARWINT	(INT_VECTOR_IRQ0+13)
ALIGN	16
HalExIHWINT14:
	HARWINT	(INT_VECTOR_IRQ0+14)
ALIGN	16
HalExIHWINT15:
	HARWINT	(INT_VECTOR_IRQ0+15)
ALIGN	16
HalExIHWINT16:
	HARWINT	(INT_VECTOR_IRQ0+16)
ALIGN	16
HalExIHWINT17:
	HARWINT	(INT_VECTOR_IRQ0+17)
	
ALIGN	16
HalExIHWINT18:
	HARWINT	(INT_VECTOR_IRQ0+18)
	
ALIGN	16
HalExIHWINT19:
	HARWINT	(INT_VECTOR_IRQ0+19)
	
ALIGN	16
HalExIHWINT20:
	HARWINT	(INT_VECTOR_IRQ0+20)
	
ALIGN	16
HalExIHWINT21:
	HARWINT	(INT_VECTOR_IRQ0+21)

ALIGN	16
HalExIHWINT22:
	HARWINT	(INT_VECTOR_IRQ0+22)
ALIGN	16
HalExIHWINT23:
	HARWINT	(INT_VECTOR_IRQ0+23)
				
ALIGN	16
HalExIApicIPISchedul:
	HARWINT	INT_VECTOR_APIC_IPI_SCHEDUL		
ALIGN	16
HalExIApicSVR:
	HARWINT	INT_VECTOR_APIC_SVR	
ALIGN	16
HalExIApicTimer:
	HARWINT	INT_VECTOR_APIC_TIMER	
ALIGN	16
HalExIApicThermal:
	HARWINT	INT_VECTOR_APIC_THERMAL	
ALIGN	16
HalExIApicPerformonitor:
	HARWINT	INT_VECTOR_APIC_PERFORM	
ALIGN	16
HalExIApicLint0:
	HARWINT	INT_VECTOR_APIC_LINTO	
ALIGN	16
HalExIApicLint1:
	HARWINT	INT_VECTOR_APIC_LINTI	
ALIGN	16
HalExIApicError:
	HARWINT	INT_VECTOR_APIC_ERROR

ALIGN	16
HalExSAPICall:
	EXSAPICALL
ALIGN	16
HalASMRetFromUserMode:
	RESTOREALL
